export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_FAILED = 'MOVIES_FAILED';
export const ADD_MOVIES = 'ADD_MOVIES';

export const PEOPLE_LOADING = 'PEOPLE_LOADING';
export const PEOPLE_FAILED = 'PEOPLE_FAILED';
export const ADD_PEOPLE = 'ADD_PEOPLE';